name: ManHunt
version: 1
main: me.chili.Manhunt.Main
api-version: 1.15
authors: [Chili]
description: Custom Manhunt

commands:
  kbd:
    description: supra
    usage: /<command>
    aliases: opengui